# <center>TP Prise en main SQL/Python </center>

<div style="text-align: center;">
    <img src="../images/sqlbase.png" width="600" height="300">
</div>

___

Il existe deux manières de taper des lignes de commandes SQL dans un Jupyter Notebook : 
- avec des décorateurs pour taper directement des lignes de commandes sql
- avec des queries

# Avec les décorateurs

In [1]:
import csv, sqlite3, pandas

con = sqlite3.connect("liste_eleve.sqlite")
cur = con.cursor()

In [2]:
%load_ext sql

In [6]:
#Si la base est dans un dossier data : %sql sqlite:///data/liste_eleve.sqlite
%sql sqlite:///liste_eleve.sqlite

In [7]:
%%sql 
SELECT Nom FROM liste_eleve;

 * sqlite:///liste_eleve.sqlite
Done.

[('ABBAD',),
 ('ABD EL NABI',),
 ('ABDELOUAHED',),
 ('ABED',),
 ('ABIDOGOUN',),
 ('ABOUE',),
 ('ABOULRAS',),
 ('ABUNIAWAN',),
 ('ACHIBANE',),
 ('ADELAIDE',),
 ('ADENET',),
 ('ADJOVI',),
 ('AFZAA',),
 ('AGHA-KASSAB',),
 ('AGUERA',),
 ('AHMADY',),
 ('AHMED',),
 ('AHMED',),
 ('AIT GHERBI',),
 ('AIT SELLAMET',),
 ('AKITANI',),
 ('AKKARI',),
 ('AKPA',),
 ('ALAHOUM',),
 ('ALBIC',),
 ('ALICTO',),
 ('ALILI',),
 ('ALLICHE',),
 ('ALMEIDA GOMES',),
 ('ALVES DE PAULA NOGUEIRA',),
 ('AMALOU',),
 ('AMANI',),
 ('AMORIM',),
 ('ANDRADE FONSECA DA GRAÇA',),
 ('ANDRE BENTO',),
 ('ANTONIO PANZU',),
 ('APPERY',),
 ('ARAB',),
 ('ARAHNG BEKA',),
 ('ARAMBOL',),
 ('ARIYARATNA',),
 ('ASSAS',),
 ('ASSEMIEN',),
 ('ATAKOUN',),
 ('ATALLAH',),
 ('AUBRAS',),
 ('AUDIRAC',),
 ('AYED',),
 ('AZLAOUI',),
 ('AZZOUZ',),
 ('BA',),
 ('BACAR',),
 ('BACH',),
 ('BACHA',),
 ('BAH',),
 ('BAH',),
 ('BAH',),
 ('BAH',),
 ('BAH',),
 ('BAHROUN',),
 ('BAILLON',),
 ('BALASKA',),
 ('BALIRY',),
 ('BALLE BIOL',),
 ('BALLEYGUIER',),
 ('BAMBA',),
 ('BAMBA',),
 ('BAMBA',),
 ('BANGURA',),
 ('BAPTISTA',),
 ('BARBOTIN',),
 ('BARRE',),
 ('BARRY',),
 ('BARRY',),
 ('BARRY',),
 ('BARRY',),
 ('BARRY',),
 ('BARRY',),
 ('BARTOLOMEU PIRES',),
 ('BARUTI',),
 ('BARZOLA LIRA',),
 ('BAZAS',),
 ('BAZIN',),
 ('BEA',),
 ('BEGUE',),
 ('BEKIRI',),
 ('BEKIRI',),
 ('BELARBI',),
 ('BELGHITH',),
 ('BELHAJ',),
 ('BELKACEM',),
 ('BELLAHCENE',),
 ('BELLAKHDER',),
 ('BELLEC',),
 ('BELLILI',),
 ('BELTOU',),
 ('BEN AICHA',),
 ('BEN ALI',),
 ('BEN ARFA',),
 ('BEN SALAH',)]

In [18]:
%%sql
CREATE VIEW vue_eleve AS
SELECT Nom, Prénom, "Né(e) le"
FROM liste_eleve;

 * sqlite:///data/liste_eleve.sqlite
Done.

[]

In [19]:
%%sql
SELECT name FROM sqlite_master WHERE type='view';

 * sqlite:///data/liste_eleve.sqlite
Done.

[('vue_eleve',)]

In [20]:
%%sql
SELECT * FROM vue_eleve;

 * sqlite:///data/liste_eleve.sqlite
Done.

[('ABBAD', 'Chaima', '26-Feb-2002'),
 ('ABD EL NABI', 'Hazem', '11-Aug-2003'),
 ('ABDELOUAHED', 'Noureddine', '20-Mar-1986'),
 ('ABED', 'Yannis', '07-Nov-2000'),
 ('ABIDOGOUN', 'Alexandre', '12-May-2004'),
 ('ABOUE', 'Dylan', '13-Apr-2003'),
 ('ABOULRAS', "M'bark", '30-Oct-2001'),
 ('ABUNIAWAN', 'Lance', '25-Jun-2004'),
 ('ACHIBANE', 'Yassine', '22-Mar-2002'),
 ('ADELAIDE', 'Grégoire', '27-Jun-2001'),
 ('ADENET', 'Dany-Dann', '02-Mar-2002'),
 ('ADJOVI', 'Nadir', '03-Jan-2000'),
 ('AFZAA', 'Abdellah', '29-Jan-2000'),
 ('AGHA-KASSAB', 'Angéla', '10-Jun-2000'),
 ('AGUERA', 'Alane', '12-Jul-2001'),
 ('AHMADY', 'Rahmkhoda', '14-Jun-2001'),
 ('AHMED', 'Chaima', '05-Dec-2002'),
 ('AHMED', 'Ethan', '08-Dec-2002'),
 ('AIT GHERBI', 'Eddy', '25-Sep-2002'),
 ('AIT SELLAMET', 'Rayane', '14-Nov-2003'),
 ('AKITANI', 'Aude', '08-Dec-1999'),
 ('AKKARI', 'Yanice', '14-Nov-2000'),
 ('AKPA', 'Djehoury', '30-Jul-2001'),
 ('ALAHOUM', 'Ines', '28-Jan-2001'),
 ('ALBIC', 'Anastasia', '20-Mar-2003'),
 ('ALICTO', 'Mhel Francis', '08-Nov-2001'),
 ('ALILI', 'Lina', '24-Jan-2002'),
 ('ALLICHE', 'Idir', '29-Jan-2004'),
 ('ALMEIDA GOMES', 'Francisco', '13-Dec-2000'),
 ('ALVES DE PAULA NOGUEIRA', 'Clara', '04-Dec-2002'),
 ('AMALOU', 'Lydia', '02-Sep-2003'),
 ('AMANI', 'Bilal', '02-Sep-2002'),
 ('AMORIM', 'Nicolas', '19-Apr-2002'),
 ('ANDRADE FONSECA DA GRAÇA', 'Elda', '01-Jul-1999'),
 ('ANDRE BENTO', 'Junior Manuel', '11-Mar-2001'),
 ('ANTONIO PANZU', 'Jeruscha Inès', '19-Oct-2004'),
 ('APPERY', 'Alexis', '22-Jan-2003'),
 ('ARAB', 'Ibrahim', '05-Mar-2001'),
 ('ARAHNG BEKA', 'Charles Eric', '13-Nov-2003'),
 ('ARAMBOL', 'Tom', '17-Apr-2002'),
 ('ARIYARATNA', 'Shérine', '11-Mar-2004'),
 ('ASSAS', 'Hamza', '21-Sep-2003'),
 ('ASSEMIEN', 'Christ', '13-Jun-2004'),
 ('ATAKOUN', 'Ouaïna', '04-Mar-2004'),
 ('ATALLAH', 'Amine', '03-May-2004'),
 ('AUBRAS', 'Anthony', '05-Nov-2002'),
 ('AUDIRAC', 'Estelle', '01-Jul-2003'),
 ('AYED', 'Samir', '12-Dec-2001'),
 ('AZLAOUI', 'Hakim', '07-Dec-2002'),
 ('AZZOUZ', 'Yanis', '30-Nov-2002'),
 ('BA', 'Abdine', '19-Aug-2000'),
 ('BACAR', 'Idriss', '29-Sep-1999'),
 ('BACH', 'Annwenn', '18-Nov-2002'),
 ('BACHA', 'Enzo', '06-May-1999'),
 ('BAH', 'Abdoulaye', '26-May-2001'),
 ('BAH', 'Abdul Aziz', '03-Dec-2001'),
 ('BAH', 'Aïcha', '07-Nov-2003'),
 ('BAH', 'Alpha', '20-Feb-2001'),
 ('BAH', 'Mamadou Oury', '14-Apr-2002'),
 ('BAHROUN', 'Idris', '22-Oct-2000'),
 ('BAILLON', 'Mathieu', '26-Aug-2003'),
 ('BALASKA', 'Romane', '19-Oct-2003'),
 ('BALIRY', 'Erwan', '03-Feb-2004'),
 ('BALLE BIOL', 'Djayelola Karina', '28-Mar-1973'),
 ('BALLEYGUIER', 'Léo', '21-Sep-2001'),
 ('BAMBA', 'Karidja', '25-Sep-2002'),
 ('BAMBA', 'Kuoï Bi Abdul Kader', '05-Apr-2002'),
 ('BAMBA', 'Namawa', '19-Feb-2003'),
 ('BANGURA', 'Mohamed', '12-Feb-2002'),
 ('BAPTISTA', 'Thibault', '31-Jan-2003'),
 ('BARBOTIN', 'Ange-Demba', '06-Sep-2002'),
 ('BARRE', 'Océane', '14-Apr-2004'),
 ('BARRY', 'Boubacar', '03-Dec-2003'),
 ('BARRY', 'Ibrahima', '27-Feb-2002'),
 ('BARRY', 'Mamadou Boye', '22-Oct-2002'),
 ('BARRY', 'Mamadou Sansy', '01-May-2002'),
 ('BARRY', 'Ramatoulaye', '15-Jun-2001'),
 ('BARRY', 'Saydou', '05-Nov-2004'),
 ('BARTOLOMEU PIRES', 'Jennifer', '14-Oct-2001'),
 ('BARUTI', 'Joshua', '30-Apr-2003'),
 ('BARZOLA LIRA', 'Alex Sebastian', '15-Feb-2002'),
 ('BAZAS', 'Wiryam', '29-Nov-2003'),
 ('BAZIN', 'Noah', '28-Oct-2003'),
 ('BEA', 'Armel', '14-Dec-2002'),
 ('BEGUE', 'William', '12-Mar-2004'),
 ('BEKIRI', 'Barâa', '14-Mar-2001'),
 ('BEKIRI', 'Wail', '28-Feb-2003'),
 ('BELARBI', 'Samir', '24-Aug-2002'),
 ('BELGHITH', 'Jamel', '26-Apr-2004'),
 ('BELHAJ', 'Siham', '27-Dec-2003'),
 ('BELKACEM', 'Nouredine', '19-Apr-2002'),
 ('BELLAHCENE', 'Fouad', '13-Oct-2004'),
 ('BELLAKHDER', 'Mehdi', '11-Oct-2001'),
 ('BELLEC', 'Ylan', '10-Jan-2003'),
 ('BELLILI', 'Alan', '09-Jul-2002'),
 ('BELTOU', 'Mael', '10-Oct-2003'),
 ('BEN AICHA', 'Regueya', '06-Mar-1999'),
 ('BEN ALI', 'Areham', '29-Nov-2001'),
 ('BEN ARFA', 'Marouane', '01-Feb-2001'),
 ('BEN SALAH', 'Abdelkader', '14-Jan-2003')]

# Avec les Queries

In [17]:
# Exécuter une requête SQL et stocker le résultat dans un DataFrame pandas
import csv, sqlite3, pandas

query = "SELECT * FROM liste_eleve"
df = pd.read_sql(query, con)

# Afficher DataFrame
print(df)

            Nom      Prénom     Né(e) le Prénom d'usage      Sexe  Classe  \
0         ABBAD      Chaima  26-Feb-2002                  Féminin   THCRS
1   ABD EL NABI       Hazem  11-Aug-2003                 Masculin
2   ABDELOUAHED  Noureddine  20-Mar-1986                 Masculin
3          ABED      Yannis  07-Nov-2000                 Masculin
4     ABIDOGOUN   Alexandre  12-May-2004                 Masculin   2MCV1
..          ...         ...          ...            ...       ...     ...
95       BELTOU        Mael  10-Oct-2003                 Masculin  1MELEC
96    BEN AICHA     Regueya  06-Mar-1999                  Féminin
97      BEN ALI      Areham  29-Nov-2001                 Masculin
98     BEN ARFA    Marouane  01-Feb-2001                 Masculin
99    BEN SALAH  Abdelkader  14-Jan-2003                 Masculin   1ARED

   Projet d'accompagnement Allergies  Majeur  \
0                                     Majeur
1                                     Majeur
2                                     Majeur
3                                     Majeur
4                                     Majeur
..                     ...       ...     ...
95                                    Majeur
96                                    Majeur
97                                    Majeur
98                                    Majeur
99                                    Majeur

                                   Formation  \
0   2CAP2  COMMER.SERV.HOTEL-CAFE-RESTAURANT
1   2NDPRO METIERS ELECT. ENVIRON. CONNECTES
2
3   TLEPRO VENTE (PROSPECT.NEGO.SUIV.CLIENT)
4   2NDPRO MET. RELATION CLIENT 2NDE COMMUNE
..                                       ...
95  1ERPRO METIERS ELECT. ENVIRON. CONNECTES
96
97
98
99  1ERPRO SYST.NUM.OPT.B AUD.RES.EQUIP.DOM.

                                Groupes                 Toutes les options
0                                                              ANGLAIS LV1
1                                                              ANGLAIS LV1
2                                                              ANGLAIS LV1
3                  Musculation Tle G1 R          ANGLAIS LV1, ESPAGNOL LV2
4   2MCV1FRANCA, 2MCV1MATHS, 2MCV1VENTP          ANGLAIS LV1, ESPAGNOL LV2
..                                  ...                                ...
95            1MELECCONSTR, 1MELECMATHS  ANGLAIS LV1, ACCOMPAGNEMT. PERSO.
96                                               ANGLAIS LV1, ESPAGNOL LV2
97                                                             ANGLAIS LV1
98                                                             ANGLAIS LV1
99              1AREDCONSTR, 1AREDMATHS                        ANGLAIS LV1

[100 rows x 12 columns]